# Generated by Django 3.2.7 on 2021-10-05 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='project_id',
            new_name='project',
        ),
    ]
